# Generated by Django 5.1.7 on 2025-04-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_company',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
