# Generated by Django 5.1.4 on 2025-01-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.TextField(default='Untitle'),
            preserve_default=False,
        ),
    ]
