# Generated by Django 5.1.7 on 2025-04-27 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=datetime.datetime(2025, 4, 27, 8, 55, 56, 91015, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
